

define(function () {
  return {
    "In the preparation":"In the preparation",
    "FIlled": "FIlled%",
    "Cumulative bonus valuation": "Cumulative bonus valuation",
    "Yesterday's bonus valuation": "Yesterday's bonus valuation",
    "Bonus account balance": "Bonus account balance",
    "Bonus valuation": "Bonus valuation",
    "Date": "Date",
    "Management": "Management",
    "Coin Records": "Coin Records",
    "Income Records": "Income Records",
    "Income Records": " Income Records",
    "Coin": "Coin",
    "Valuation": "Valuation",
    "Time for the token": "Time for the token",
    "Exclusive coin number": "Exclusive coin number",
    "United coin number": "United coin number",
    "Coin Management": "Coin Management",
    "Time to market": "Time to market",
    "Type": "Type",
    "Please enter price or amount": "Please enter price or amount",
    "Please input buy amount": "Please input buy amount",
    "Please input sell amount": "Please input sell amount",
    "Main area": "Main",
    "No Trading Market": "No Trading Market",
    "Yesterday reward": "Yesterday reward",
    "See All": "See All",
    "My 24h Order History": "My 24h Order History",
    "See All": "More",
    'Canceled': 'Canceled',
    'Completed': 'Completed',
    'details': "Details",
    'Part Completed': 'Part Deal',
    'Hide all canceled': 'Hide all canceled',
    "direction": "Side",
    "Insufficient available balance": "Insufficient available balance",
    "1.3EX provides you with a strong API, through which you can enjoy services such as Market Query, Automatic Trading, etc. View How To Use via API documentation.": "1.3EX provides you with a strong API, through which you can enjoy services such as Market Query, Automatic Trading, etc. View How To Use via API documentation.",
    "2.Each user can create 1 API Keys at most.": "2.Each user can create 1 API Keys at most.",
    "3.Store your Secret Key somewhere safe. It will not be shown again.": "3.Store your Secret Key somewhere safe. It will not be shown again.",
    "Creating an API private key provides access to markets and real-time trading services on 3EX.": "Creating an API private key provides access to markets and real-time trading services on 3EX.",
    "con": ".",
    "Confirm delete API KEY?": "Confirm delete API KEY?",
    "Store your Secret Key somewhere safe. It will not be shown again": "Store your Secret Key somewhere safe. It will not be shown again",
    "Each user can create 1 API Keys at most.": "Each user can create only one API. If you want to recreate the API, delete the current API.",
    "API settings": "API settings",
    "Creating the API key": "Creating the API key",
    "remove": "Delete",
    "Price": "Price",
    "Amount": "Amount",
    "Average Price": "Average Price",
    "Total": "Total",
    "API Setting": "API Setting",
    "Download APP": "Download APP",
    "View API documentation": " View API documentation ",
    "people": "People",
    "No bonus": "No bonus",
    "Trade to get TEX, you get a daily bonus!": "Trade to get TEX, you get a daily bonus!",
    "Cumulative revenue to be distributed in yesterday（BTC）": "Revenue  to be distributed yesterday (BTC)",
    "Mining output TEX's amount of yesterday": "Mining output TEX's amount of yesterday",
    "Current Mining output TEX's amount": "Total Mining output TEX's amount",
    "Trading reward": "Trade",
    "New user award": "New user",
    "Invite rewards": "Invite",
    "Invitation": "Invitation",
    "Invitation Code": "Invitation Code",
    "Copy code": "Copy code",
    "Exclusive registration link": "Exclusive registration link",
    "Copy and link to share": "Copy link to share",
    "Cashback": "Cashback",
    "Invite Total": " Invite Total",
    "Cashback ratio": "Cashback ratio",
    "Today's Cashback": "Today's Cashback",
    "Total Cashback": " Total Cashback",
    "Cashback History": " Cashback History",
    "The browser doesn't support it": "The browser doesn't support it",
    "Invite Rebate": "Invitation Cashback",
    "Bonus records": "Bonus records",
    "The TEX record": "The TEX record",
    "Cumulative bonus valuation": "Cumulative bonus valuation",
    "Bonus account balance": "Bonus balance",
    "Bonus valuation (in the form of virtual currency)": "Bonus valuation (in the form of virtual currency)",
    "Bonus count": "Bonus count",
    "Value": "Value",
    "Trading reward": "Trade",
    "Succeed": "Succeed",
    "In certification": "In certification",
    "Recertification": "Recertification",
    "Invite code (Optional)": "Invite code (Optional)",
    "Submit": "Submit",
    "No data": "No data",
    "Account": "Account",
    "LoginTime": "LoginTime",
    "Login IP": "Login IP",
    "Estimate value": "Estimate value",
    "Identity must be authenticated before withdrawal": "Identity must be authenticated before withdrawal",
    "You have passed identity verification": "approved",
    'Google Authenticator have not been bound': 'Has not yet been bound',
    "Services": "Services",
    'Canceled': "Canceled",
    "Exchange": "Exchange",
    'Please login again': 'Please login again',
    "Support": "Support",
    "Submit a request": "Submit a request",
    "Clause Instruction": "Clause Instruction",
    "Contact Us": "Contact Us",
    "Social": "Social",
    "Total": "Total",
    "page": "page",
    "Jump to": "Jump to",
    "next page": "Next page",
    "Previous page": "Previous page",
    "Explorer": "Explorer",
    "coin info": "Info",
    "marketcap": "Marketcap",
    "max supply": "Max Supply",
    "circulating supply": "Circulating Supply",
    "issue price": "Issue Price",
    "issue date": "Issue Date",
    "website": "Website",
    "explorer": "Explorer",
    "white paper": "White Paper",
    "introduction": "Introduction",
    "exchange": "Exchange",
    "favorites": "Favorites",
    "usdtmarket": "USDT Markets",
    "btcmarket": "BTC Markets",
    "ethmarket": "ETH Markets",
    "24h-change": "24h Change",
    "24h-high": "24h High",
    "24h-low": "24h Low",
    "24h-volume": "24h Volume",
    "about": "About",
    "terms": "Terms",
    "privacy": "Privacy",
    "fees": "Fees",
    "order management": "Orders",
    "last-price": "Last Price",
    "hourline": "Line",
    "1m":"1min",
    "5m":"5min",
    "15m":"15min",
    "30m":"30min",
    "1H":"1hour",
    "2H":"2hour",
    "4H":"4hour",
    "6H":"6hour",
    "12H":"12hour",
    "Consensus": "Consensus",
    "Authoritative media recommended": "Authoritative media recommended",
    "Recommend": "Recommend",
    "Recommend Introduce": "Recommend Introduce",
    "Price": "Price",
    "24h changed%": "24h changed%",
    "24h vol": "24h vol",
    "Issue price changed%": "Issue changed%",
    "hour": "H",
    "dayline": "1day",
    "weekline": "1week",
    "monthline": "1mon",
    "you have no open orders": "You have no open orders.",
    " The recharge address is valid for 24 hours. After expiration, please click again to get the recharge address": " The recharge address is valid for 24 hours. After expiration, please click again to get the recharge address.",
    "limitorder": "Limit",
    "Market": "Market",
    "The best market price_buy": "The best market price",
    "The best market price": "The best market price",
    "buy": "Buy",
    "sell": "Sell",
    "balance": "Balance",
    "to trade": "to trade",
    "all": "All",
    "buylist": "Buy",
    "sellist": "Sell",
    "trade-history": "Trade History",
    "funds": "Funds",
    "cnyvalue": "USD Value",
    "balances": "Balances",
    "search": "Search",
    "deposit": "Deposit",
    "select deposit coin": "Select coin/token",
    "charge address": "Deposit Address",
    "deposit warining": "Send only {0} to this deposit address. Sending any other coin or token to this address may result in the loss of your deposit.",
    "show qr code": "Show QR Code",
    "copy address": "Copy Address",
    "withdrawal": "Withdrawals",
    "withdraw": "Withdraw",
    "select withdrawal coin": "Select coin/token",
    "make an identity authentication": "Not yet authenticated",
    "The actual you will get should be greater than the minimum withdrawal limit": "The actual you will get should be greater than or equal to  the minimum withdrawal limit.",

    "in order": "In order",
    "total balance": "Total balance",
    "withdrawal warning": "Do not withdraw directly to a crowdfund or ICO. We will not credit your account with tokens from that sale.",
    "withdrawal address": "Withdrawal Address",
    "please input your new withdrawal address below": "Please enter your withdrawal address",
    "withdrawamount": "Amount",
    "24h withdrawal limit": "24h Withdrawal Limit",
    "minimum amount of withdrawal": "Minimum withdrawal",
    "withdrawmax": "Max",
    "available balance": "Available balance",
    "actual": "You Will Get",

    "withdrawal tips": "After making a withdrawal, you can track its progress on the <a href='#/property/rechargeList'>history page</a>.",
    "transaction history": "Transaction History",
    "coin": "Coin",
    "notransaction": "You have no transaction history.",
    "order mangerment": "Orders",
    "exchage order": "Orders",
    "open orders": "Open Orders",
    "trade history": "Order History",
    "time": "Date",
    "pair": "Pair",
    "market": "Market",
    "type": "Type",
    "price": "Price",
    "amount": "Amount",
    "amt": "Amount",
    "Order History": "Order History",
    "total": "Total",
    "action": "Type",
    "fullcancel": "Cancel all",
    "cancel": "Cancel",
    "status": "Status",
    "Executed": "Executed",
    "dealprice": "Price",
    "orderfilled": "Filled",
    "tradetotal": "Total",
    "user center": "Account",
    "logout": "Logout",
    "last login": "Last Login",
    "my account": "Account",
    "current level": "Current Level",
    "fee": "Fee",
    "identity authentication": "Identity Authentication",
    "immediate authentication": "Immediate Authentication",
    "identity verification  is awaiting approval": "Under review",
    "you have passed identity verification.": "You ave passed identity verification.",
    "rejected": "Rejected",
    "submit again": "Submit Again",
    "used for login": "Used for login",
    "change": "Change",
    "edit": "Edit",
    "modify login password": "Modify Login Password",
    "old password": "Old Password",
    "new password": "New Password",
    "confirm new password": "Confirm Password",
    "change password": "Change Password",
    "google authentication": "Google Authentication",
    "googleoperate": "Used for withdrawals and security modifications",
    "disable": "Disable",
    "download app": "Download App",
    "scan qr": "Scan QR-code",
    "print a backup": "Backup Key",
    "download and install google authentication app": "Download and install the Google Authentication app",
    "i have installed the app": "I have installed the app",
    "if you have any problem with scanning the qr code enter this code manually into the app.": "If you are unable to scan the QR code",
    "use google authentication app to scan this qr code": "Scan this QR code in the Google Authentication app",
    "i have scanned the qr code": "I have scanned the qr code",
    "prev step": "Previous step",
    "please save this key on paper. this key will allow you to recover your google authentication in case of phone loss.": "Please save this Key on paper. This Key will allow you to recover your Google Authentication in case of phone loss.",
    "resetting your google authentication requires opening a support ticket and takes at least 7 days to process.": "Resetting your Google authentication via customer service email at support@3ex.com may take at least 7 days to process.",
    "i have already written down the 16-digit key": "I have already written down the 16-Digit Key",
    "key": "16-digit Key",
    "login password": "Login Password",
    "enter key": "Enter Key",
    "2fa code": "Google Authentication Code",
    "enter sms code": "Enter sms code",
    "send sms code": "SMS Code",
    "phone code": "Phone Authentication",
    "google authentication code": "Google Authentication Code",
    "enable google authentication": "Enable Google Authentication",
    "Please enter the withdrawal amount": "Please enter the withdrawal amount",
    "id type": "ID Type",
    "last name": "Surname",
    "first name": "Given name",
    "identity card": "Identity card",
    "id number": "Valid Identity Card",
    "identity card is wrong": "Identity card is wrong",
    "identity card front side": "Take photo of personal details",
    "please make sure that the photo is complete and clearly visible in jpg format.": "Please make sure that the photo is complete and clearly visible, in JPG or PNG format. Id card must be in the valid period.",
    "example": "Example",
    "identity card back side": "Take photo of front cover",
    "please make sure that the photo is complete and clearly visible in jpg format. id card must be in the valid period.": "Please make sure that the photo is complete and clearly visible, in JPG or PNG format. Id card must be in the valid period.",
    "cn-handphoto": "Selfie With Photo ID And Note",
    "please provide a photo of you holding your identity card front side. in the same picture make a reference to 3EX and today's date displayed. make sure your face is clearly visible and that all passport details are clearly readable.": "Please provide a photo of you holding your Identity Card front side. In the same picture, make a reference to 3EX and today's date displayed. Make sure your face is clearly visible and that all passport details are clearly readable.",
    "widthdrawsubmit": "Submit",
    "enter phone number": "Phone Number",
    "password": "Password",
    'Are you sure you want to cancel all?': 'Are you sure you want to cancel all?',
    "login now": "Log in",
    'Tips': 'Tips',
    "forgot password": "Forgot Password",
    "not on 3ex yet？": "Not on 3EX yet?",
    "drag the left slider toverify": "Drag the slider to verify",
    "2AF": "Two-factor Authentication",
    "create account": "Register",
    "phone number": "Phone Number",
    "verification code": "Code",
    "registeragree": "I agree to 3EX's",
    "next step": "Next",
    "already registered": "Already Registered",
    "login": "Log in",
    "register": "Register",
    "retrieve the password": "Reset Password",
    "sms authentication code": "SMS Code",
    "Bonus History": "Bonus History",
    "TEX Reward history": " TEX Reward history",
    "reset password": "Reset Password",
    "enter password": "Password",
    "enter password again": "Enter Password Again",
    "the password has been modified and landed": "The password has been changed",
    "click the jump login page": "Login",
    "price alert": "Your purchase price {0} is higher than the market average price {1}%, please be sure to check and confirm!",
    "price alert low": "Your purchase price {0} is higher than the market average price {1}%, please be sure to check and confirm!",
    "price sell_alert": "Your sale price {0} is lower than the market average price {1}%, please be sure to check and confirm!",
    'login to 3EX': 'Login to 3EX',
    'no records': 'No records',
    'tips': 'Tips',
    'published at': 'Published at',
    'change password tips': 'For security reasons, withdrawal is not allowed in 24 hours when changed password',
    'old password must not be blank': 'Old password is required',
    'new password must not be blank': 'New password is required',
    'wrong new password format': 'Wrong new password format, 8~16 digits with number and letters',
    'comfirm password must not be blank': 'Comfirm password is required',
    'new password does not match new password': 'Comfirm password does not match new password',
    'wrong confirm password format': 'Wrong confirm password format',
    'upload': 'Upload',
    "volume": "volume",
    'ok': 'Confirm',
    "Min Limit": 'Min Limit：',
    "Your balance is not enough": 'Your balance is not enough',
    'key must not be blank': 'Key is required',
    'login password must not be blank': 'Password is required',
    'wrong password format': 'Wrong password format, 8~18 digits with number and letters',
    'google authentication code must not be blank': 'Google authentication code is required',
    'phone must not be blank': "Phone must not be blank",
    'wrong phone number': "Wrong phone number",
    "sms authentication code must not be blank": "SMS authentication code is required",
    "chinese": "Chinese",
    "english": "English",
    "user": "User",
    "Suspended": "Suspended",
    "Operation failed": 'Operation failed',
    "announcement": "News",
    "help": "Help",
    "succeeded": "Succeed",
    "max buy": 'Max buy',
    'wrong code': 'Wrong code',
    'code': 'Code',
    'Operation failed': 'Operation failed',
    'Operation successfully': 'Operate successfully',
    'Lack of necessary parameters': 'Lack of necessary parameters',
    'Sliding validation failed': 'Sliding validation failed',
    'User name or password error': 'ERROR Incorrect username or password',
    'Unknown request sequence': 'Unknown request order',
    'authentication failed': 'Authentication failed',
    'Wrong mobile phone number': 'Wrong mobile phone number',
    'The operation is too frequent, please try it later': 'The operation is too frequent, please try again later',
    'Google verification code error': 'Google Verification Code Error',
    'Get the verification code first': 'Please get the verification code first',
    'Login first': 'Login first',
    'Account number already exists': 'Account already exists',
    'Different passwords, please re-enter': 'The passwords you entered are different. Please re-enter them',
    'Password format error, please enter 8-16 bits must contain a combination of letters and Numbers': 'Password format error, please enter 8-16 bits must contain a combination of letters and Numbers',
    'The phone number is not registered': 'The phone number is not registered',
    'The system is busy please try again later': 'The system is busy please try again later',
    'Accuracy is wrong': 'Wrong precision',
    'Pair does not exist': 'Trading pairs do not exist',
    'Token is not allowed to be traded': 'Tokens are not allowed to trade',
    'The total number of transactions is less than the threshold': 'Total turnover less than threshold',
    'The unit price is less than the lowest': 'Unit price below minimum unit price',
    'The number is less than the minimum number of transactions': 'Quantity less than minimum transaction quantity',
    'Insufficient user balance': 'Insufficient balance',
    'The order status has changed': 'Order status has changed',
    'Abnormal order status': 'Order Status exception',
    'The old password is not the same as the new one': 'The old password cannot be the same as the new password',
    'Password error': 'wrong password',
    'Secret lose efficacy': 'Key invalidation',
    'Secret error': 'Key error',
    'The user has bound the Google validator': 'User has bound Google Validator',
    'Lack of positive photo of id card': 'Lack of document positive photo',
    'No id reverse photos are available': 'Missing front negative photos',
    'No id card to hold a photo': 'Lack of handheld ID photos',
    'File is not exists': 'File does not exist',
    'Tokens are not allowed to be recharged': 'Tokens are not allowed to recharge',
    'Please authenticate first': 'Please authenticate first',
    'Embodiment lock': 'Your withdrawal status is locked',
    'The withdrawal amount is wrong': 'The withdrawal amount is wrong',
    'Withdrawal of tokens is not allowed': 'Withdrawal of tokens is not allowed',
    'Withdrawals are less than the threshold': 'The amount of withdrawal shall not be less than the minimum amount of withdrawal',
    'The amount of withdrawal should be greater than the commission charge': 'The amount of withdrawal shall be greater than the withdrawal fee',
    'Address format error': 'Withdrawal address format error',
    'Withdrawals have been exhausted today': 'Withdrawals have been exhausted today',
    'Unknown request address': 'Unknown request address',
    'Undefined business': 'Undefined business',
    'Undefined method': 'Undefined methods',
    'Empty body': 'Empty body',
    'Decrypt failed': 'Decryption failure',
    'Article details': 'Article details',
    "Please login again":"Please login again",
    'google authenticator': 'Google Authenticator',
    'enable': 'Enable',
    'disable': 'Disable',
    'create': 'Create',
    'estimate value': 'Estimate value',
    'trade': 'Trade',
    'submit': 'Submit',
    'withdraw disabled reason': 'Widthrawal disabled，you may have：<br/>1、Changed password in last 24 hours。<br>2、Disabled Google Authenticator in last 24 hours。',
    'exceed 24 hour max amount': 'Exceed 24 hour max amount',
    'minimum withdraw amount': 'Minimum withdraw amount',
    'not enough balance': 'Not enough balance',
    'order history': 'Trade History',
    'failed': 'Failed',
    'uploading': 'Uploading',
    'loading': 'Loading',
    'waiting upload': 'Waiting upload',
    'proccessing': 'Proccessing',
    'copy failed': 'Coping failed，please copy manually',
    'disable google authenticator': 'Disable google authenticator',
    'google authenticator code must not be blank': 'Google authenticator code is required',
    'change authenticator tips': 'For security reasons, withdrawal is not allowed in 24 hours when disabled google authenticator',
    'history': 'History',
    'resend': 'Resend',
    'click here to login': 'Click here to login',
    'please select coin/token': 'Please select coin/token',
    'fav': 'Fav',
    "TIPS": "TIPS",
    "Confirm": "Confirm",
    "Cancel": "Cancel",
    'Coupons do not exist': 'Coupons do not exist',
    'Coupons are locked or have been bound': 'Coupons are locked or have been bound',
    'You are using the same type of coupon': 'You are using the same type of coupon',
    'Failure of coupons or unopened activities': 'Failure of coupons or unopened activities',
    'Coupons are non reusable types,You have used the same type of coupons': 'Coupons are non reusable types,You have used the same type of coupons',
    'Only 100 pairs of the same transaction are allowed': 'Only 100 pairs of the same transaction are allowed',
    'Pair No trading allowed': 'Pair No trading allowed',
    "Wallet Maintenance, Deposit  Suspended": "Wallet Maintenance, Deposit  Suspended",
    "Wallet Maintenance, Withdraw Suspended": "Wallet Maintenance, Withdraw Suspended",
    'new password and old password': 'New password and old password must be different',
    'login password is required': 'Login password is required',
    'or': 'or'
  }
});




