
define(function(){
    return {
        "In the preparation":"活动暂未开始",
        "My 24h Order History":"我的24小时历史委托",
        "See All":"查看更多",
        "Creating an API private key provides access to markets and real-time trading services on 3EX.":"创建API密钥可以让您使用3EX的行情查询，实时交易等服务。",
       "con":"了解如何使用您的API Keys。",
       "1.3EX provides you with a strong API, through which you can enjoy services such as Market Query, Automatic Trading, etc. View How To Use via API documentation.":"1、3EX为您提供了强大的API，您可以通过 API 使用行情查询、自动交易等服务。通过 API 文档 查看如何使用。",
       "2.Each user can create 1 API Keys at most.":"2、每个用户只能创建一个API，如果想重新创建API，请删除当前的API",
       "3.Store your Secret Key somewhere safe. It will not be shown again.":"3、请将您的Secret Key存储在安全的地方，将不再展示，如果忘记，请删除后重新创建",
        "remove":"删除",
        "Store your Secret Key somewhere safe. It will not be shown again":"仅显示1次，遗失后不可找回，请务必妥善保存",
       "API Setting":"API管理",
       "Each user can create 1 API Keys at most.":"每个用户只能创建一个API，如果想重新创建API，请删除当前的API",
       "API settings":"API设置",
        "View API documentation":" API文档 ",
        "Creating the API key":"创建API密钥",
        "Download APP":"App下载",
        "people":"人",
        "No bonus":"当前暂无分红！",
        "Trade to get TEX, you get a daily bonus!":"通过交易获得TEX，每日即可参与收入分红！",
        "Cumulative revenue to be distributed in yesterday（BTC）":"昨日交易分配收入累计折合BTC",
        "Mining output TEX's amount of yesterday":"昨日交易挖矿产生TEX数量",
        "Current Mining output TEX's amount":"累计已挖出TEX数量",
        "Trading reward":"交易奖励",
        "New user award":"新人奖励", 
        "Invite rewards":"邀请奖励",
        "FIlled":"成交率%",
        "Cumulative bonus valuation":"累计分红估值",
        "Yesterday's bonus valuation":"昨日分红估值",
        "Bonus account balance":"分红账户余额",
        "Bonus valuation":"分红估值",
        "Date":"日期",
        "Yesterday reward":"昨日奖励",

        "Invitation":"我的邀请",
        "Invitation Code":"我的邀请码",
        "Copy code":"复制邀请码",
        "Exclusive registration link":"专属注册链接",
        "Copy and link to share":"复制链接邀请",
        "Cashback":"我的返佣",
        "Invite Total":" 邀请人数",
        "Cashback ratio":"返佣比例",
        "Today's Cashback":"今日返佣",
        "Total Cashback":" 累计返佣",
        "Cashback History":" 返佣记录",
        "The browser doesn't support it":"该浏览器不支持自动复制",
        "Invite Rebate":"邀请返利",
        "Succeed":"已完成",
        "In certification":"认证中",
        "Recertification":"重新认证",
        "Submit":"开始认证",
        "Services":"服务",
        "Exchange":"交易中心",
        "Support":"支持",
        "Submit a request":"提交工单",
        "Clause Instruction":"条款声明",
        "Contact Us":"联系我们",
        "Social":"社区",
        "Total":"共",
        "page":"页",
        "Jump to":"跳到",
        "Explorer":"区块查询地址",
        "exchange":"币币交易",
        "favorites":"自选",
        "usdtmarket":"usdt市场",
        "btcmarket":"btc市场",
        "ethmarket":"eth市场",
        "24h-change":"24h涨跌",
        "24h-high":"24h最高价",
        "24h-low":"24h最低价",
        "volume":"成交量",
        "24h-volume":"24h成交量",
        "about":"关于我们",
        "terms":"服务协议",
        "privacy":"隐私声明",
        "fees":"费率标准",
        "order management":"订单管理",
        "last-price":"最新价",
        "hourline":"分时",
        "hour":"小时",
        "1m":"1m",
        "5m":"5m",
        "15m":"15m",
        "30m":"30m",
        "1H":"1H",
        "2H":"2H",
        "4H":"4H",
        "6H":"6H",
        "12H":"12H",
        "dayline":"日线",
        "Please enter the withdrawal amount":"请输入提现数量",
        "weekline":"周线",
        "monthline":"月线",
        "you have no open orders":"暂无当前委托",
        "No data":"暂无数据",
        "limitorder":"限价",
        "Market":"市价",
        'Hide all canceled':'隐藏已撤销',
        'details':"详情",
        "The best market price_buy":"市场最优价格买入",
        "The best market price":"市场最优价格卖出",
        "buy":"买入",
        "sell":"卖出",
        "Account":"账户名称",
        "LoginTime":"登陆时间",
        "Login IP":"登录IP",
        "Estimate value":"资产估值",
        "balance":"余额",
        "to trade":"进行交易",
        "all":"全部",
        "buylist":"买单",
        "sellist":"卖单",
        "Please enter price or amount":"请输入价格或数量",
        "trade-history":"最新成交",
        "funds":"资产管理",
        "cnyvalue":"CNY估值",
        "balances":"我的资产",
        "search":"搜索",
        "deposit":"充值",
        "select deposit coin":"请选择币种",
        "charge address":"充值地址",
        "deposit warining":"禁止向{0}地址充值除{0}以外的资产，任何被充入{0}地址的非{0}资产将不可被找回。",
        "show qr code":"展示二维码",
        "copy address":"复制到剪切板",
        "withdraw":"提现",
        "The recharge address is valid for 24 hours. After expiration, please click again to get the recharge address":"充值地址有效期时间为24小时，过期后请重新点击获取充值地址。",
        "select withdrawal coin":"请选择币种",
        "in order":"冻结",
        "Please input buy amount":"请输入买入量",
        "Please input sell amount":"请输入卖出量",
        "total balance":"总额",
        "withdrawal warning":"注意 请勿直接提现至众筹或ico地址.我们不会处理未来代币的发放。",
        "withdrawal address":"提现地址",
        "please input your new withdrawal address below":"请输入提现地址",
        "withdrawamount":"提现数量",
        "24h withdrawal limit":"24h提现额度",
        "minimum amount of withdrawal":"最小提现金额",
        "withdrawmax":"全部提现",
        "available balance":"可用余额",
        "Insufficient available balance":"可用余额不足",
        "direction":"方向",
        "actual":"实际到账",
        "withdrawal tips":"您可以在 <a href='#/property/rechargeList'>充值提现记录</a> 页面跟踪状态。",
        "transaction history":"充值提现记录",
        "Bonus History":"分红记录",
        "TEX Reward history":"TEX奖励记录",
        "coin":"币种",
        "Time to market":"上币时间",
        "notransaction":"暂无充值提现记录.",
        "exchage order":"币币订单",
        "open orders":"当前委托",
        "trade history":"历史成交",
        "time":"时间",
        "pair":"市场",
        "type":"类型",
        "Type":"推荐方式",
        "Exclusive":"独家推荐",   
        "United":"联合推荐",   
        "price":"价格",
        "amount":"数量",
        "Main area":"主区",
        "amt":"数量",
        "total":"金额",
        "Confirm delete API KEY?":"确认删除API KEY？",
        "action":"类型",
        "fullcancel":"全撤",
        "cancel":"撤单",
        "status":"状态",
        "Executed":"已成交",
        "Price":"委托价格",
        "Order History":"历史委托",
        "Amount":"委托量",
        "Average Price":"成交均价",
        "Total":"成交总额",
        "dealprice":"成交价格",
        "orderfilled":"成交数量",
        "tradetotal":"成交金额",
        "user center":"用户中心",
        "logout":"退出",
        "last login":"上次登录",
        "my account":"我的账户",
        "current level":"当前等级",
        "Time for the token":"令牌发放时间",
        "Exclusive coin number":"独家推荐币种个数",
        "United coin number":"联合推荐币种个数",
        "Coin Management":"管理币种",
        "fee":"手续费",
        "identity authentication":"身份认证",
        "immediate authentication":"开始身份认证",
        "Identity must be authenticated before withdrawal":"提现之前必须要进行身份认证",
        "identity verification  is awaiting approval":"身份认证审核中",
        "You have passed identity verification":"身份认证审核通过",
        "make an identity authentication":"请进行身份认证",
        "The actual you will get should be greater than the minimum withdrawal limit":"实际到账应大于等于最小提现额度",
        "rejected":"身份认证失败 ",
        "submit again":"重新认证",
        "used for login":"登录时使用",
        "change":"涨跌",
        "edit": "修改",
        "modify login password":"修改登录密码",
        "old password":"原密码",
        "new password":"新密码",
        "confirm new password":"确认新密码",
        "change password":"修改密码",
        "google authentication":"谷歌验证",
        "googleoperate":"提现，修改密码，及安全设置时用以验证谷歌二次验证",
        "disable":"关闭",
        "Suspended":"暂停",
        "download app":"下载app",
        "scan qr":"扫描二维码",
        "print a backup":"备份密钥",
        "download and install google authentication app":"下载并安装谷歌验证器app",
        "i have installed the app":"我已安装好app",
        "if you have any problem with scanning the qr code enter this code manually into the app.":"如果您无法扫描二维码可以将该16位密钥手动输入到谷歌验证app中",
        "use google authentication app to scan this qr code":"使用谷歌验证器app扫描该二维码",
        "i have scanned the qr code":"我已经完成二维码扫描",
        "prev step":"上一步",
        "please save this key on paper. this key will allow you to recover your google authentication in case of phone loss.":"请将16位密钥记录在纸上，并保存在安全的地方。如遇手机丢失，你可以通过该密钥恢复你的谷歌验证。",
        "resetting your google authentication requires opening a support ticket and takes at least 7 days to process.":"通过客服邮箱support@3ex.com重置你的谷歌验证，可能需要至少7天时间来处理。",
        "i have already written down the 16-digit key":"我已经写下了16位密钥",
        "key":"16位密钥",
        "login password":"登录密码",
        "enter key":"请输入密钥",
        "2fa code":"请输入谷歌验证码",

        "coin info":"币种信息",
        "marketcap":"市值",
        "max supply":"发行总量",
        "circulating supply":"流通数量",
        "issue price":"发行价格",
        "issue date":"发行日期",
        "website":"官网",
        "explorer":"区块链浏览器",
        "white paper":"白皮书",
        "introduction":"介绍",
        "Bonus records":"分红纪录",
        "The TEX record":"TEX奖励记录",
        "Cumulative bonus valuation":"历史累计分红估值",
        "Bonus account balance":"分红账户余额",
        "Bonus valuation (in the form of virtual currency)":"分红估值（分红以虚拟币的形式发放）",
        "Bonus count": "分红量",
        "Value": "估值",
        "Trading reward":"交易奖励",
        "enter sms code": "输入手机验证码",
        "send sms code": "发送验证码",
        "phone code":"手机验证",
        "google authentication code":"谷歌验证码",
        "enable google authentication":"开启谷歌验证",
        "id type":"证件类型",
        "last name":"姓氏",
        "last name is null":"姓氏不能为空",
        "first name":"名字",
        "first name is null":"名字不能为空",
        "identity card":"身份证",
        "identity card is null":"身份证不能为空",
        "identity card is wrong":"身份证格式不对",
        "id number":"证件号码",
        "identity card front side":"身份证人像面",
        "provide photo":"上传图片",
        "please make sure that the photo is complete and clearly visible in jpg format.":"请确保照片的内容完整并清晰可见，仅支持jpg或png图片格式。",
        "example":"示例",
        "identity card back side":"身份证国徽面",
        "please make sure that the photo is complete and clearly visible in jpg format. id card must be in the valid period.":"请确保照片的内容完整并清晰可见，身份证必须在有效期内，仅支持jpg和png格式",
        "cn-handphoto":"手持本人身份证正面照和个人签字",
        "please provide a photo of you holding your identity card front side. in the same picture make a reference to 3ex and today's date displayed. make sure your face is clearly visible and that all passport details are clearly readable.":"请您上传一张手持身份证正面照和个人签字的照片，个人签字的内容包含“3EX”和当前日期。请确保照片和个人签字的内容清晰可见。",
        "widthdrawsubmit":"提交",
        "enter phone number":"请输入手机号",
        "password":"密码",
        'Are you sure you want to cancel all?':'您确定要取消所有当前委托吗？',
        "login now":"立即登录",
        "forgot password":"忘记密码",
        "not on 3ex yet？":"还没注册？",
        "drag the left slider toverify":"拖动滑块完成拼图",
        "2AF":"二次验证",
        "create account":"注册",
        "phone number":"手机号",
        "verification code":"验证码",
        "registeragree":"我已阅读并同意",
        "next step":"下一步",
        "next page":"下一页",
        "Previous page":"上一页",
        "already registered":"已经注册",
        "login":"登录",
        "register":"完成",
        "Operation failed":'操作失败',
        "retrieve the password":"找回密码",
        "sms authentication code":"短信验证码",
        "reset password":"重置密码",
        "enter password":"请输入密码",
        "enter password again":"请再次输入密码",
        "the password has been modified and landed":"密码已修改成功，去登录",
        "click the jump login page":"点击跳转登录页面",
        'loading': '加载中...',
        'market':'市场',
        'price alert': '您的买入价格 {0} 高于市场平均价格 {1}%，请务必检查确认！',
        'price sell_alert': '您的卖出价格 {0} 低于市场平均价格 {1}%，请务必检查确认！',
        "Min Limit":'最小交易额为：',
        "Your balance is not enough":'您的余额不足',

        "login to 3EX":"登录3ex",
        'no records':'暂无委托',
        'tips': '温馨提示',
        'published at': '发布时间',
        'change password tips': '为了您的账户安全，登录密码修改后24小时内不允许提现',
        'old password must not be blank': '原密码不能为空',
        'new password must not be blank': '新密码不能为空',
        'wrong new password format': '新密码格式不对,数字加字母8至16位',
        'comfirm password must not be blank': '确认新密码不能为空',
        'new password does not match new password': '确认密码与密码不相同',
        'wrong confirm password format': '确认密码格式不对,数字加字母8至16位',
        'upload': '上传',
        'ok': '确定',
        'key must not be blank': '16位密钥不为空',
        'login password must not be blank': '密码不能为空',
        'wrong password format': '密码格式不对,数字加字母8至16位',
        'google authentication code must not be blank' : '谷歌验证码不能为空',
        'phone must not be blank': "手机号不能为空",
        'wrong phone number': "手机号格式不对",
        "sms authentication code must not be blank":"验证码不能为空",
        "chinese": "中文",
        "english": "英文",
        "user": "用户",
        "announcement": "官方公告",
        "help": "新手帮助",
        "Management":"上币管理",
        "Coin Records":"上币记录",
        "Income Records":"项目收入记录",
        "Income Records":" 收入记录",
        "Coin":"项目",
        "Valuation":"估值",
        "succeeded": "成功",
        "max buy": '最多购买',
        'wrong code': '请输入正确验证码',
        'code': '验证码',
        "Consensus":'共识区',
        "Authoritative media recommended":"权威区块链媒体推荐",
        "Recommend":"推荐媒体",
        "Recommend Introduce":"推荐语",
        "Price":"最新价",
        "24h changed%":"24h涨跌幅",
        "24h vol":"24h成交量",
        "Please login again":"请先登录",
        "Issue price changed%":"发行价涨幅",
        'Please login again':'会话过期,请重新登录',
        'Operation failed':'操作失败',
        'Operation successfully':'操作成功',
        'Lack of necessary parameters':'缺少必要参数',
        'Sliding validation failed':'滑动验证失败',
        'User name or password error':'用户名或密码错误',
        'Unknown request sequence':'未知请求顺序',
        'authentication failed':'验证失败',
        'Wrong mobile phone number':'手机号错误',
        'The operation is too frequent, please try it later':'操作太频繁，请稍后再试',
        'Google verification code error':'谷歌验证码错误',
        'Get the verification code first':'请先获取验证码',
        'Login first':'请先登录',
        'Account number already exists':'账号已存在',
        'Different passwords, please re-enter':'两次密码不同，请重新输入',
        'Password format error, please enter 8-16 bits must contain a combination of letters and Numbers':'密码设置格式错误，请输入8-16位必须同时含有字母和数字的组合',
        'The phone number is not registered':'手机号码未注册',
        'The system is busy please try again later':'系统繁忙请稍后再试',
        'Accuracy is wrong':'精度有误',
        'Pair does not exist':'交易对不存在',
        'Token is not allowed to be traded':'代币不允许交易',
        'The total number of transactions is less than the threshold':'成交总额小于阈值',
        'The unit price is less than the lowest':'单价低于最低单价',
        'The number is less than the minimum number of transactions':'数量小于最小交易数量',
        'Insufficient user balance':'用户余额不足',
        'The order status has changed':'订单状态已经更改',
        'Abnormal order status':'订单状态异常',
        'The old password is not the same as the new one':'旧密码与新密码不能相同',
        'Password error':'密码错误',
        'Secret lose efficacy':'密钥失效',
        'Secret error':'密钥错误',
        'Google Authenticator have not been bound':'尚未绑定谷歌验证',
        'The user has bound the Google validator':'用户已绑定谷歌验证器',
        'Lack of positive photo of id card':'缺少证件正面照片',
        'No id reverse photos are available':'缺少正面反面照片',
        'No id card to hold a photo':'缺少身份证手持照片',
        'File is not exists':'文件不存在',
        'Tokens are not allowed to be recharged':'代币不允许充值',
        'Please authenticate first':'请先身份验证',
        'Embodiment lock':'您的提现状态被锁定',
        'The withdrawal amount is wrong':'提现数量错误',
        'Withdrawal of tokens is not allowed':'代币不允许提现',
        'Withdrawals are less than the threshold':'提现数量不可小于最小提现数量',
        'The amount of withdrawal should be greater than the commission charge':'提现数量应大于提现手续费',
        'Address format error':'提现地址格式错误',
        'Withdrawals have been exhausted today':'今日提现额度已用尽',
        'Unknown request address':'为止请求地址',
        'Undefined business':'未定义的业务',
        'Undefined method':'未定义的方法',
        'Empty body':'包体为空',
        'Decrypt failed':'解密失败',
        'google authenticator': '谷歌验证器',
        'enable': '开启',
        'disable': '关闭',
        'create': '添加',
        'estimate value': '当前估值',
        'trade': '交易',
        "No Trading Market":"暂无交易市场",
        "Invite code (Optional)":"邀请码（选填）",
        'submit': '提交',
        'Canceled':'已撤销',
        'Completed':'完全成交',
        'Part Completed':'部分成交',
        'withdraw disabled reason': '您的提现状态被锁定，可能有以下原因：<br/>1、24小时内修改过密码。<br>2、24小时内关闭谷歌验证。',
        'exceed 24 hour max amount': '已超过24小时最大提现额度',
        'minimum withdraw amount': '最小提现额度',
        'not enough balance': '余额不足',
        'order history': '成交记录',
        'failed': '失败',
        'uploading': '正在上传',
        'waiting upload': '待上传',
        'proccessing': '处理中',
        'copy failed': '复制失败，请手动选择复制！',
        'disable google authenticator': '解除谷歌验证',
        'google authenticator code must not be blank': '谷歌验证码不能为空',
        'change authenticator tips': '为了您的账户安全，关闭谷歌验证后24小时内不允许提现',
        'Article details':'文章详情',
        'history': '充值提现记录',
        'resend': '重新发送',
        'click here to login': '转到登录页面',
        'please select coin/token': '请选择币种',
        'fav':'自选',
        'please select coin/token': '请选择币种',
        "TIPS":"提示",
        "Confirm":"确认",
        'Canceled':"已取消",
        "Cancel":"取消",
        'Tips':'提示',
        'Pair No trading allowed':'交易对不允许交易',
        "Wallet Maintenance, Deposit  Suspended":"钱包维护中，充值暂停",
        "Wallet Maintenance, Withdraw Suspended":"钱包维护中，提现暂停 ",

        'Coupons do not exist':'优惠券不存在',
        'Coupons are locked or have been bound':'优惠券被锁定或者已被绑定',
        'You are using the same type of coupon':'不可重复使用相同类型的优惠券',
        'Failure of coupons or unopened activities':'未在活动激活时间内',
        'Coupons are non reusable types,You have used the same type of coupons':'该优惠券每个用户只可使用一次',
        'Only 100 pairs of the same transaction are allowed':'同一交易对只允许存在100单',

        'new password and old password': '新密码不能与原密码相同',
        'login password is required': '登录密码不能为空',
        'or': '或'
    }
});